// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package templator.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Templator module

	/**
	* By default the PDF that is generated looks for the app at Core.getApplicationRootUrl()
	* Use this constant to change this for example to account for proxies or tunnels
	* 
	* e.g. http:\\\\example.ngrok.io
	*/
	public static java.lang.String getApplicationURLOverrideOPTIONAL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Templator.ApplicationURLOverrideOPTIONAL");
	}

	/**
	* used to asymetrically encrypt data before sending it to the external templator service
	* this is public key, so it can not be used to decrypt the data, Therefore, it can be distributed as plain text.
	* There is no need to change this value unless you are hosting your own service
	*/
	public static java.lang.String getEncryptionKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Templator.EncryptionKey");
	}

	public static java.lang.String getServiceEndpoint()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Templator.ServiceEndpoint");
	}

	public static java.lang.String getServiceFunctionKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Templator.ServiceFunctionKey");
	}
}