// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package templator.proxies;

public enum ENUM_PaperFormat
{
	Letter(new java.lang.String[][] { new java.lang.String[] { "en_US", "Letter" } }),
	Legal(new java.lang.String[][] { new java.lang.String[] { "en_US", "Legal" } }),
	Tabloid(new java.lang.String[][] { new java.lang.String[] { "en_US", "Tabloid" } }),
	Ledger(new java.lang.String[][] { new java.lang.String[] { "en_US", "Ledger" } }),
	A0(new java.lang.String[][] { new java.lang.String[] { "en_US", "A0" } }),
	A1(new java.lang.String[][] { new java.lang.String[] { "en_US", "A1" } }),
	A2(new java.lang.String[][] { new java.lang.String[] { "en_US", "A2" } }),
	A3(new java.lang.String[][] { new java.lang.String[] { "en_US", "A3" } }),
	A4(new java.lang.String[][] { new java.lang.String[] { "en_US", "A4" } }),
	A5(new java.lang.String[][] { new java.lang.String[] { "en_US", "A5" } }),
	A6(new java.lang.String[][] { new java.lang.String[] { "en_US", "A6" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_PaperFormat(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
