// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package templator.proxies;

public class PageHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pageHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Templator.PageHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MicroflowName("MicroflowName"),
		ParameterEntityName("ParameterEntityName"),
		ParameterObjectId("ParameterObjectId"),
		HideControlElements("HideControlElements"),
		HideDialogs("HideDialogs"),
		HideValidations("HideValidations"),
		DisableBootstrapPrintStyling("DisableBootstrapPrintStyling");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PageHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Templator.PageHelper"));
	}

	protected PageHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pageHelperMendixObject)
	{
		if (pageHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Templator.PageHelper", pageHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Templator.PageHelper");

		this.pageHelperMendixObject = pageHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PageHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static templator.proxies.PageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return templator.proxies.PageHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static templator.proxies.PageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new templator.proxies.PageHelper(context, mendixObject);
	}

	public static templator.proxies.PageHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return templator.proxies.PageHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MicroflowName
	 */
	public final java.lang.String getMicroflowName()
	{
		return getMicroflowName(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowName
	 */
	public final java.lang.String getMicroflowName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MicroflowName.toString());
	}

	/**
	 * Set value of MicroflowName
	 * @param microflowname
	 */
	public final void setMicroflowName(java.lang.String microflowname)
	{
		setMicroflowName(getContext(), microflowname);
	}

	/**
	 * Set value of MicroflowName
	 * @param context
	 * @param microflowname
	 */
	public final void setMicroflowName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microflowname)
	{
		getMendixObject().setValue(context, MemberNames.MicroflowName.toString(), microflowname);
	}

	/**
	 * @return value of ParameterEntityName
	 */
	public final java.lang.String getParameterEntityName()
	{
		return getParameterEntityName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterEntityName
	 */
	public final java.lang.String getParameterEntityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParameterEntityName.toString());
	}

	/**
	 * Set value of ParameterEntityName
	 * @param parameterentityname
	 */
	public final void setParameterEntityName(java.lang.String parameterentityname)
	{
		setParameterEntityName(getContext(), parameterentityname);
	}

	/**
	 * Set value of ParameterEntityName
	 * @param context
	 * @param parameterentityname
	 */
	public final void setParameterEntityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parameterentityname)
	{
		getMendixObject().setValue(context, MemberNames.ParameterEntityName.toString(), parameterentityname);
	}

	/**
	 * @return value of ParameterObjectId
	 */
	public final java.lang.String getParameterObjectId()
	{
		return getParameterObjectId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterObjectId
	 */
	public final java.lang.String getParameterObjectId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParameterObjectId.toString());
	}

	/**
	 * Set value of ParameterObjectId
	 * @param parameterobjectid
	 */
	public final void setParameterObjectId(java.lang.String parameterobjectid)
	{
		setParameterObjectId(getContext(), parameterobjectid);
	}

	/**
	 * Set value of ParameterObjectId
	 * @param context
	 * @param parameterobjectid
	 */
	public final void setParameterObjectId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parameterobjectid)
	{
		getMendixObject().setValue(context, MemberNames.ParameterObjectId.toString(), parameterobjectid);
	}

	/**
	 * @return value of HideControlElements
	 */
	public final java.lang.Boolean getHideControlElements()
	{
		return getHideControlElements(getContext());
	}

	/**
	 * @param context
	 * @return value of HideControlElements
	 */
	public final java.lang.Boolean getHideControlElements(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HideControlElements.toString());
	}

	/**
	 * Set value of HideControlElements
	 * @param hidecontrolelements
	 */
	public final void setHideControlElements(java.lang.Boolean hidecontrolelements)
	{
		setHideControlElements(getContext(), hidecontrolelements);
	}

	/**
	 * Set value of HideControlElements
	 * @param context
	 * @param hidecontrolelements
	 */
	public final void setHideControlElements(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hidecontrolelements)
	{
		getMendixObject().setValue(context, MemberNames.HideControlElements.toString(), hidecontrolelements);
	}

	/**
	 * @return value of HideDialogs
	 */
	public final java.lang.Boolean getHideDialogs()
	{
		return getHideDialogs(getContext());
	}

	/**
	 * @param context
	 * @return value of HideDialogs
	 */
	public final java.lang.Boolean getHideDialogs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HideDialogs.toString());
	}

	/**
	 * Set value of HideDialogs
	 * @param hidedialogs
	 */
	public final void setHideDialogs(java.lang.Boolean hidedialogs)
	{
		setHideDialogs(getContext(), hidedialogs);
	}

	/**
	 * Set value of HideDialogs
	 * @param context
	 * @param hidedialogs
	 */
	public final void setHideDialogs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hidedialogs)
	{
		getMendixObject().setValue(context, MemberNames.HideDialogs.toString(), hidedialogs);
	}

	/**
	 * @return value of HideValidations
	 */
	public final java.lang.Boolean getHideValidations()
	{
		return getHideValidations(getContext());
	}

	/**
	 * @param context
	 * @return value of HideValidations
	 */
	public final java.lang.Boolean getHideValidations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HideValidations.toString());
	}

	/**
	 * Set value of HideValidations
	 * @param hidevalidations
	 */
	public final void setHideValidations(java.lang.Boolean hidevalidations)
	{
		setHideValidations(getContext(), hidevalidations);
	}

	/**
	 * Set value of HideValidations
	 * @param context
	 * @param hidevalidations
	 */
	public final void setHideValidations(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hidevalidations)
	{
		getMendixObject().setValue(context, MemberNames.HideValidations.toString(), hidevalidations);
	}

	/**
	 * @return value of DisableBootstrapPrintStyling
	 */
	public final java.lang.Boolean getDisableBootstrapPrintStyling()
	{
		return getDisableBootstrapPrintStyling(getContext());
	}

	/**
	 * @param context
	 * @return value of DisableBootstrapPrintStyling
	 */
	public final java.lang.Boolean getDisableBootstrapPrintStyling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DisableBootstrapPrintStyling.toString());
	}

	/**
	 * Set value of DisableBootstrapPrintStyling
	 * @param disablebootstrapprintstyling
	 */
	public final void setDisableBootstrapPrintStyling(java.lang.Boolean disablebootstrapprintstyling)
	{
		setDisableBootstrapPrintStyling(getContext(), disablebootstrapprintstyling);
	}

	/**
	 * Set value of DisableBootstrapPrintStyling
	 * @param context
	 * @param disablebootstrapprintstyling
	 */
	public final void setDisableBootstrapPrintStyling(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean disablebootstrapprintstyling)
	{
		getMendixObject().setValue(context, MemberNames.DisableBootstrapPrintStyling.toString(), disablebootstrapprintstyling);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pageHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final templator.proxies.PageHelper that = (templator.proxies.PageHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Templator.PageHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
