// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package templator.proxies;

public class PDFFile extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Templator.PDFFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		PDFFile_User("Templator.PDFFile_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PDFFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Templator.PDFFile"));
	}

	protected PDFFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pDFFileMendixObject)
	{
		super(context, pDFFileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Templator.PDFFile", pDFFileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Templator.PDFFile");
	}

	/**
	 * @deprecated Use 'PDFFile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static templator.proxies.PDFFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return templator.proxies.PDFFile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static templator.proxies.PDFFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new templator.proxies.PDFFile(context, mendixObject);
	}

	public static templator.proxies.PDFFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return templator.proxies.PDFFile.initialize(context, mendixObject);
	}

	public static java.util.List<templator.proxies.PDFFile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<templator.proxies.PDFFile> result = new java.util.ArrayList<templator.proxies.PDFFile>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Templator.PDFFile" + xpathConstraint))
			result.add(templator.proxies.PDFFile.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of PDFFile_User
	 */
	public final system.proxies.User getPDFFile_User() throws com.mendix.core.CoreException
	{
		return getPDFFile_User(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFFile_User
	 */
	public final system.proxies.User getPDFFile_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PDFFile_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PDFFile_User
	 * @param pdffile_user
	 */
	public final void setPDFFile_User(system.proxies.User pdffile_user)
	{
		setPDFFile_User(getContext(), pdffile_user);
	}

	/**
	 * Set value of PDFFile_User
	 * @param context
	 * @param pdffile_user
	 */
	public final void setPDFFile_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User pdffile_user)
	{
		if (pdffile_user == null)
			getMendixObject().setValue(context, MemberNames.PDFFile_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PDFFile_User.toString(), pdffile_user.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final templator.proxies.PDFFile that = (templator.proxies.PDFFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Templator.PDFFile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
