// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package templator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Must be used in a user context, so no scheduled events.
 * 
 * See https://www.notion.so/gajduk/Templator-Docs-aa00c14bcb8946e8b3b9bb80e6dea2ce#0fda5b5a025b4b61ac040b011514e8f1 for more details.
 */
public class GeneratePDFForCurrentUser extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __PDFFile_;
	private system.proxies.FileDocument PDFFile_;
	private java.lang.String Microflow_;
	private IMendixObject Parameter_;
	private IMendixObject __CustomOptions_;
	private templator.proxies.Options CustomOptions_;

	public GeneratePDFForCurrentUser(IContext context, IMendixObject PDFFile_, java.lang.String Microflow_, IMendixObject Parameter_, IMendixObject CustomOptions_)
	{
		super(context);
		this.__PDFFile_ = PDFFile_;
		this.Microflow_ = Microflow_;
		this.Parameter_ = Parameter_;
		this.__CustomOptions_ = CustomOptions_;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.PDFFile_ = __PDFFile_ == null ? null : system.proxies.FileDocument.initialize(getContext(), __PDFFile_);

		this.CustomOptions_ = __CustomOptions_ == null ? null : templator.proxies.Options.initialize(getContext(), __CustomOptions_);

		// BEGIN USER CODE
		return GeneratePDFForSpecificUser.generatePDF(getContext(), this.PDFFile_,  this.Microflow_, this.Parameter_, this.CustomOptions_, null);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GeneratePDFForCurrentUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
