// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class AdPhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.AdPhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		AdPhoto_Advertisement("MyFirstModule.AdPhoto_Advertisement");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AdPhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.AdPhoto"));
	}

	protected AdPhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject adPhotoMendixObject)
	{
		super(context, adPhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.AdPhoto", adPhotoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.AdPhoto");
	}

	/**
	 * @deprecated Use 'AdPhoto.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.AdPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.AdPhoto.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.AdPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.AdPhoto(context, mendixObject);
	}

	public static myfirstmodule.proxies.AdPhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.AdPhoto.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.AdPhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.AdPhoto> result = new java.util.ArrayList<myfirstmodule.proxies.AdPhoto>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.AdPhoto" + xpathConstraint))
			result.add(myfirstmodule.proxies.AdPhoto.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of AdPhoto_Advertisement
	 */
	public final myfirstmodule.proxies.Advertisement getAdPhoto_Advertisement() throws com.mendix.core.CoreException
	{
		return getAdPhoto_Advertisement(getContext());
	}

	/**
	 * @param context
	 * @return value of AdPhoto_Advertisement
	 */
	public final myfirstmodule.proxies.Advertisement getAdPhoto_Advertisement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Advertisement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AdPhoto_Advertisement.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Advertisement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AdPhoto_Advertisement
	 * @param adphoto_advertisement
	 */
	public final void setAdPhoto_Advertisement(myfirstmodule.proxies.Advertisement adphoto_advertisement)
	{
		setAdPhoto_Advertisement(getContext(), adphoto_advertisement);
	}

	/**
	 * Set value of AdPhoto_Advertisement
	 * @param context
	 * @param adphoto_advertisement
	 */
	public final void setAdPhoto_Advertisement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Advertisement adphoto_advertisement)
	{
		if (adphoto_advertisement == null)
			getMendixObject().setValue(context, MemberNames.AdPhoto_Advertisement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AdPhoto_Advertisement.toString(), adphoto_advertisement.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.AdPhoto that = (myfirstmodule.proxies.AdPhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.AdPhoto";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
