// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Advertisement
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject advertisementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Advertisement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ad_type("ad_type"),
		available_from("available_from"),
		deposit("deposit"),
		price("price"),
		active("active"),
		name("name"),
		squareFoot("squareFoot"),
		description("description"),
		tags("tags"),
		location("location"),
		comment("comment"),
		needs_change("needs_change"),
		is_valid("is_valid"),
		municipality("municipality"),
		city("city"),
		documents_correct("documents_correct"),
		Create_Advertisement("MyFirstModule.Create_Advertisement"),
		AdPhoto_Advertisement("MyFirstModule.AdPhoto_Advertisement"),
		Activate_Advertisement("MyFirstModule.Activate_Advertisement"),
		Review_Advertisement("MyFirstModule.Review_Advertisement");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Advertisement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Advertisement"));
	}

	protected Advertisement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject advertisementMendixObject)
	{
		if (advertisementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Advertisement", advertisementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Advertisement");

		this.advertisementMendixObject = advertisementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Advertisement.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Advertisement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Advertisement.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Advertisement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Advertisement(context, mendixObject);
	}

	public static myfirstmodule.proxies.Advertisement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Advertisement.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Advertisement> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Advertisement> result = new java.util.ArrayList<myfirstmodule.proxies.Advertisement>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Advertisement" + xpathConstraint))
			result.add(myfirstmodule.proxies.Advertisement.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of ad_type
	 * @param ad_type
	 */
	public final myfirstmodule.proxies.ad_type getad_type()
	{
		return getad_type(getContext());
	}

	/**
	 * @param context
	 * @return value of ad_type
	 */
	public final myfirstmodule.proxies.ad_type getad_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ad_type.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.ad_type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ad_type
	 * @param ad_type
	 */
	public final void setad_type(myfirstmodule.proxies.ad_type ad_type)
	{
		setad_type(getContext(), ad_type);
	}

	/**
	 * Set value of ad_type
	 * @param context
	 * @param ad_type
	 */
	public final void setad_type(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ad_type ad_type)
	{
		if (ad_type != null)
			getMendixObject().setValue(context, MemberNames.ad_type.toString(), ad_type.toString());
		else
			getMendixObject().setValue(context, MemberNames.ad_type.toString(), null);
	}

	/**
	 * @return value of available_from
	 */
	public final java.util.Date getavailable_from()
	{
		return getavailable_from(getContext());
	}

	/**
	 * @param context
	 * @return value of available_from
	 */
	public final java.util.Date getavailable_from(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.available_from.toString());
	}

	/**
	 * Set value of available_from
	 * @param available_from
	 */
	public final void setavailable_from(java.util.Date available_from)
	{
		setavailable_from(getContext(), available_from);
	}

	/**
	 * Set value of available_from
	 * @param context
	 * @param available_from
	 */
	public final void setavailable_from(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date available_from)
	{
		getMendixObject().setValue(context, MemberNames.available_from.toString(), available_from);
	}

	/**
	 * @return value of deposit
	 */
	public final java.math.BigDecimal getdeposit()
	{
		return getdeposit(getContext());
	}

	/**
	 * @param context
	 * @return value of deposit
	 */
	public final java.math.BigDecimal getdeposit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.deposit.toString());
	}

	/**
	 * Set value of deposit
	 * @param deposit
	 */
	public final void setdeposit(java.math.BigDecimal deposit)
	{
		setdeposit(getContext(), deposit);
	}

	/**
	 * Set value of deposit
	 * @param context
	 * @param deposit
	 */
	public final void setdeposit(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal deposit)
	{
		getMendixObject().setValue(context, MemberNames.deposit.toString(), deposit);
	}

	/**
	 * @return value of price
	 */
	public final java.math.BigDecimal getprice()
	{
		return getprice(getContext());
	}

	/**
	 * @param context
	 * @return value of price
	 */
	public final java.math.BigDecimal getprice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.price.toString());
	}

	/**
	 * Set value of price
	 * @param price
	 */
	public final void setprice(java.math.BigDecimal price)
	{
		setprice(getContext(), price);
	}

	/**
	 * Set value of price
	 * @param context
	 * @param price
	 */
	public final void setprice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.price.toString(), price);
	}

	/**
	 * @return value of active
	 */
	public final java.lang.Boolean getactive()
	{
		return getactive(getContext());
	}

	/**
	 * @param context
	 * @return value of active
	 */
	public final java.lang.Boolean getactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.active.toString());
	}

	/**
	 * Set value of active
	 * @param active
	 */
	public final void setactive(java.lang.Boolean active)
	{
		setactive(getContext(), active);
	}

	/**
	 * Set value of active
	 * @param context
	 * @param active
	 */
	public final void setactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.active.toString(), active);
	}

	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of squareFoot
	 */
	public final java.lang.String getsquareFoot()
	{
		return getsquareFoot(getContext());
	}

	/**
	 * @param context
	 * @return value of squareFoot
	 */
	public final java.lang.String getsquareFoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.squareFoot.toString());
	}

	/**
	 * Set value of squareFoot
	 * @param squarefoot
	 */
	public final void setsquareFoot(java.lang.String squarefoot)
	{
		setsquareFoot(getContext(), squarefoot);
	}

	/**
	 * Set value of squareFoot
	 * @param context
	 * @param squarefoot
	 */
	public final void setsquareFoot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String squarefoot)
	{
		getMendixObject().setValue(context, MemberNames.squareFoot.toString(), squarefoot);
	}

	/**
	 * @return value of description
	 */
	public final java.lang.String getdescription()
	{
		return getdescription(getContext());
	}

	/**
	 * @param context
	 * @return value of description
	 */
	public final java.lang.String getdescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.description.toString());
	}

	/**
	 * Set value of description
	 * @param description
	 */
	public final void setdescription(java.lang.String description)
	{
		setdescription(getContext(), description);
	}

	/**
	 * Set value of description
	 * @param context
	 * @param description
	 */
	public final void setdescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.description.toString(), description);
	}

	/**
	 * @return value of tags
	 */
	public final java.lang.String gettags()
	{
		return gettags(getContext());
	}

	/**
	 * @param context
	 * @return value of tags
	 */
	public final java.lang.String gettags(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tags.toString());
	}

	/**
	 * Set value of tags
	 * @param tags
	 */
	public final void settags(java.lang.String tags)
	{
		settags(getContext(), tags);
	}

	/**
	 * Set value of tags
	 * @param context
	 * @param tags
	 */
	public final void settags(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tags)
	{
		getMendixObject().setValue(context, MemberNames.tags.toString(), tags);
	}

	/**
	 * @return value of location
	 */
	public final java.lang.String getlocation()
	{
		return getlocation(getContext());
	}

	/**
	 * @param context
	 * @return value of location
	 */
	public final java.lang.String getlocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.location.toString());
	}

	/**
	 * Set value of location
	 * @param location
	 */
	public final void setlocation(java.lang.String location)
	{
		setlocation(getContext(), location);
	}

	/**
	 * Set value of location
	 * @param context
	 * @param location
	 */
	public final void setlocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.location.toString(), location);
	}

	/**
	 * @return value of comment
	 */
	public final java.lang.String getcomment()
	{
		return getcomment(getContext());
	}

	/**
	 * @param context
	 * @return value of comment
	 */
	public final java.lang.String getcomment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.comment.toString());
	}

	/**
	 * Set value of comment
	 * @param comment
	 */
	public final void setcomment(java.lang.String comment)
	{
		setcomment(getContext(), comment);
	}

	/**
	 * Set value of comment
	 * @param context
	 * @param comment
	 */
	public final void setcomment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comment)
	{
		getMendixObject().setValue(context, MemberNames.comment.toString(), comment);
	}

	/**
	 * @return value of needs_change
	 */
	public final java.lang.Boolean getneeds_change()
	{
		return getneeds_change(getContext());
	}

	/**
	 * @param context
	 * @return value of needs_change
	 */
	public final java.lang.Boolean getneeds_change(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.needs_change.toString());
	}

	/**
	 * Set value of needs_change
	 * @param needs_change
	 */
	public final void setneeds_change(java.lang.Boolean needs_change)
	{
		setneeds_change(getContext(), needs_change);
	}

	/**
	 * Set value of needs_change
	 * @param context
	 * @param needs_change
	 */
	public final void setneeds_change(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean needs_change)
	{
		getMendixObject().setValue(context, MemberNames.needs_change.toString(), needs_change);
	}

	/**
	 * @return value of is_valid
	 */
	public final java.lang.Boolean getis_valid()
	{
		return getis_valid(getContext());
	}

	/**
	 * @param context
	 * @return value of is_valid
	 */
	public final java.lang.Boolean getis_valid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.is_valid.toString());
	}

	/**
	 * Set value of is_valid
	 * @param is_valid
	 */
	public final void setis_valid(java.lang.Boolean is_valid)
	{
		setis_valid(getContext(), is_valid);
	}

	/**
	 * Set value of is_valid
	 * @param context
	 * @param is_valid
	 */
	public final void setis_valid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean is_valid)
	{
		getMendixObject().setValue(context, MemberNames.is_valid.toString(), is_valid);
	}

	/**
	 * Set value of municipality
	 * @param municipality
	 */
	public final myfirstmodule.proxies.REGION getmunicipality()
	{
		return getmunicipality(getContext());
	}

	/**
	 * @param context
	 * @return value of municipality
	 */
	public final myfirstmodule.proxies.REGION getmunicipality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.municipality.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.REGION.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of municipality
	 * @param municipality
	 */
	public final void setmunicipality(myfirstmodule.proxies.REGION municipality)
	{
		setmunicipality(getContext(), municipality);
	}

	/**
	 * Set value of municipality
	 * @param context
	 * @param municipality
	 */
	public final void setmunicipality(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.REGION municipality)
	{
		if (municipality != null)
			getMendixObject().setValue(context, MemberNames.municipality.toString(), municipality.toString());
		else
			getMendixObject().setValue(context, MemberNames.municipality.toString(), null);
	}

	/**
	 * @return value of city
	 */
	public final java.lang.String getcity()
	{
		return getcity(getContext());
	}

	/**
	 * @param context
	 * @return value of city
	 */
	public final java.lang.String getcity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.city.toString());
	}

	/**
	 * Set value of city
	 * @param city
	 */
	public final void setcity(java.lang.String city)
	{
		setcity(getContext(), city);
	}

	/**
	 * Set value of city
	 * @param context
	 * @param city
	 */
	public final void setcity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.city.toString(), city);
	}

	/**
	 * @return value of documents_correct
	 */
	public final java.lang.Boolean getdocuments_correct()
	{
		return getdocuments_correct(getContext());
	}

	/**
	 * @param context
	 * @return value of documents_correct
	 */
	public final java.lang.Boolean getdocuments_correct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.documents_correct.toString());
	}

	/**
	 * Set value of documents_correct
	 * @param documents_correct
	 */
	public final void setdocuments_correct(java.lang.Boolean documents_correct)
	{
		setdocuments_correct(getContext(), documents_correct);
	}

	/**
	 * Set value of documents_correct
	 * @param context
	 * @param documents_correct
	 */
	public final void setdocuments_correct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean documents_correct)
	{
		getMendixObject().setValue(context, MemberNames.documents_correct.toString(), documents_correct);
	}

	/**
	 * @return value of Create_Advertisement
	 */
	public final myfirstmodule.proxies.Client getCreate_Advertisement() throws com.mendix.core.CoreException
	{
		return getCreate_Advertisement(getContext());
	}

	/**
	 * @param context
	 * @return value of Create_Advertisement
	 */
	public final myfirstmodule.proxies.Client getCreate_Advertisement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Client result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Create_Advertisement.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Client.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Create_Advertisement
	 * @param create_advertisement
	 */
	public final void setCreate_Advertisement(myfirstmodule.proxies.Client create_advertisement)
	{
		setCreate_Advertisement(getContext(), create_advertisement);
	}

	/**
	 * Set value of Create_Advertisement
	 * @param context
	 * @param create_advertisement
	 */
	public final void setCreate_Advertisement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Client create_advertisement)
	{
		if (create_advertisement == null)
			getMendixObject().setValue(context, MemberNames.Create_Advertisement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Create_Advertisement.toString(), create_advertisement.getMendixObject().getId());
	}

	/**
	 * @return value of AdPhoto_Advertisement
	 */
	public final myfirstmodule.proxies.AdPhoto getAdPhoto_Advertisement() throws com.mendix.core.CoreException
	{
		return getAdPhoto_Advertisement(getContext());
	}

	/**
	 * @param context
	 * @return value of AdPhoto_Advertisement
	 */
	public final myfirstmodule.proxies.AdPhoto getAdPhoto_Advertisement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.AdPhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AdPhoto_Advertisement.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.AdPhoto.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AdPhoto_Advertisement
	 * @param adphoto_advertisement
	 */
	public final void setAdPhoto_Advertisement(myfirstmodule.proxies.AdPhoto adphoto_advertisement)
	{
		setAdPhoto_Advertisement(getContext(), adphoto_advertisement);
	}

	/**
	 * Set value of AdPhoto_Advertisement
	 * @param context
	 * @param adphoto_advertisement
	 */
	public final void setAdPhoto_Advertisement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.AdPhoto adphoto_advertisement)
	{
		if (adphoto_advertisement == null)
			getMendixObject().setValue(context, MemberNames.AdPhoto_Advertisement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AdPhoto_Advertisement.toString(), adphoto_advertisement.getMendixObject().getId());
	}

	/**
	 * @return value of Activate_Advertisement
	 */
	public final myfirstmodule.proxies.Admin getActivate_Advertisement() throws com.mendix.core.CoreException
	{
		return getActivate_Advertisement(getContext());
	}

	/**
	 * @param context
	 * @return value of Activate_Advertisement
	 */
	public final myfirstmodule.proxies.Admin getActivate_Advertisement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Admin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Activate_Advertisement.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Admin.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Activate_Advertisement
	 * @param activate_advertisement
	 */
	public final void setActivate_Advertisement(myfirstmodule.proxies.Admin activate_advertisement)
	{
		setActivate_Advertisement(getContext(), activate_advertisement);
	}

	/**
	 * Set value of Activate_Advertisement
	 * @param context
	 * @param activate_advertisement
	 */
	public final void setActivate_Advertisement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Admin activate_advertisement)
	{
		if (activate_advertisement == null)
			getMendixObject().setValue(context, MemberNames.Activate_Advertisement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Activate_Advertisement.toString(), activate_advertisement.getMendixObject().getId());
	}

	/**
	 * @return value of Review_Advertisement
	 */
	public final myfirstmodule.proxies.Agent getReview_Advertisement() throws com.mendix.core.CoreException
	{
		return getReview_Advertisement(getContext());
	}

	/**
	 * @param context
	 * @return value of Review_Advertisement
	 */
	public final myfirstmodule.proxies.Agent getReview_Advertisement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Agent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Review_Advertisement.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Agent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Review_Advertisement
	 * @param review_advertisement
	 */
	public final void setReview_Advertisement(myfirstmodule.proxies.Agent review_advertisement)
	{
		setReview_Advertisement(getContext(), review_advertisement);
	}

	/**
	 * Set value of Review_Advertisement
	 * @param context
	 * @param review_advertisement
	 */
	public final void setReview_Advertisement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Agent review_advertisement)
	{
		if (review_advertisement == null)
			getMendixObject().setValue(context, MemberNames.Review_Advertisement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Review_Advertisement.toString(), review_advertisement.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return advertisementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Advertisement that = (myfirstmodule.proxies.Advertisement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Advertisement";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
