// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Documents extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Documents";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Documents_Advertisement("MyFirstModule.Documents_Advertisement");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Documents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Documents"));
	}

	protected Documents(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentsMendixObject)
	{
		super(context, documentsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Documents", documentsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Documents");
	}

	/**
	 * @deprecated Use 'Documents.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Documents initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Documents.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Documents initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Documents(context, mendixObject);
	}

	public static myfirstmodule.proxies.Documents load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Documents.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Documents> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Documents> result = new java.util.ArrayList<myfirstmodule.proxies.Documents>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Documents" + xpathConstraint))
			result.add(myfirstmodule.proxies.Documents.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Documents_Advertisement
	 */
	public final myfirstmodule.proxies.Advertisement getDocuments_Advertisement() throws com.mendix.core.CoreException
	{
		return getDocuments_Advertisement(getContext());
	}

	/**
	 * @param context
	 * @return value of Documents_Advertisement
	 */
	public final myfirstmodule.proxies.Advertisement getDocuments_Advertisement(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Advertisement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Documents_Advertisement.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Advertisement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Documents_Advertisement
	 * @param documents_advertisement
	 */
	public final void setDocuments_Advertisement(myfirstmodule.proxies.Advertisement documents_advertisement)
	{
		setDocuments_Advertisement(getContext(), documents_advertisement);
	}

	/**
	 * Set value of Documents_Advertisement
	 * @param context
	 * @param documents_advertisement
	 */
	public final void setDocuments_Advertisement(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Advertisement documents_advertisement)
	{
		if (documents_advertisement == null)
			getMendixObject().setValue(context, MemberNames.Documents_Advertisement.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Documents_Advertisement.toString(), documents_advertisement.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Documents that = (myfirstmodule.proxies.Documents) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Documents";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
